### ISSUE TITLE
Mod Doesn't Work on 1.18.2

### ISSUE THREAD

**Issue by PhweeDev** [TheMillman/ChristmasFestivity#3]
Simply put, we cannot play this on 1.18.2. Can you update the mod to 1.18.2?

**Comment by TheMillman** [comment]
I know and it is also noted that it works for 1.18.1. However now I am working on an update for version 1.18.2 and 1.19.2, but for now I still have to finish. Check if the latest version of the mod I released last year also works for 1.18.2 if not I will do an update by Sunday.

**Comment by PhweeDev** [comment]
It only works on 1.18.1. I shall wait for the release of your 1.18.2 update.

**Comment by PhweeDev** [comment]
How's work on this going?

**Comment by TheMillman** [comment]
I'm done and I'm trying it, today or tomorrow I'll release it.
